package es.unileon.ulebank.GUI.variableAccount;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class InvestmentFundClientGUI extends JFrame {

	private JPanel contentPane;

	
	
	public InvestmentFundClientGUI() {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 1276, 840);
		contentPane = new JPanel();

		setContentPane(contentPane);
		
		
		int width = this.getToolkit().getScreenSize().width;
        int height = this.getToolkit().getScreenSize().height;

        setSize( width , height );
        
        JPanel panel = new JPanel();
        JTable tableMovements = new JTable(new DefaultTableModel(
				new Object[][] {
					{"Ejemplo1", "Ejemplo1", "Ejemplo1", "Ejemplo1"},
					{"Ejemplo2", "Ejemplo2", "Ejemplo2", "Ejemplo2"},
					{"Ejemplo3", "Ejemplo3", "Ejemplo3", "Ejemplo3"},
					{"Ejemplo4", "Ejemplo4", "Ejemplo4", "Ejemplo4"},
					{"Ejemplo5", "Ejemplo5", "Ejemplo5", "Ejemplo5"},
					{"Ejemplo6", "Ejemplo6", "Ejemplo6", "Ejemplo6"},
					{"Ejemplo7", "Ejemplo7", "Ejemplo7", "Ejemplo7"},
					{"Ejemplo8", "Ejemplo8", "Ejemplo8", "Ejemplo8"},
					},
				new String[] {
					"Fecha", "ID", "Participaciones", "Precio","Tasa por incumplimiento","Empleado","Estado"
				}
			));
		tableMovements.setSurrendersFocusOnKeystroke(true);
		tableMovements.setColumnSelectionAllowed(true);
		tableMovements.setCellSelectionEnabled(true);
		tableMovements.getColumnModel().getColumn(0).setPreferredWidth(50);
		tableMovements.getColumnModel().getColumn(1).setPreferredWidth(200);
		tableMovements.setPreferredScrollableViewportSize(new Dimension(1000, 300));
		JScrollPane scrollPane = new JScrollPane(tableMovements);

		panel.add(scrollPane, BorderLayout.CENTER);
		
		JButton buyInvestmentFund = new JButton("Contratar fondos de inversion");
		buyInvestmentFund.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				InvestmentFundGUI nextWindow = new InvestmentFundGUI();
				nextWindow.setVisible(true);
				setVisible(false);
			}
		});
		
		JButton cancelInvestmentFund = new JButton("Cancelar fondos de inversion");
		cancelInvestmentFund.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				InvestmentFundSalesGUI nextWindow = new InvestmentFundSalesGUI();
				nextWindow.setVisible(true);
				setVisible(false);
			}
		});
		
		JButton variableAccount = new JButton("Cuenta Variable");
		variableAccount.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				VariableAccountGUI nextWindow = new VariableAccountGUI();
				nextWindow.setVisible(true);
				setVisible(false);
			}
		});
        
        
		
		GroupLayout gl_contentPane = new GroupLayout(contentPane);
		contentPane.setLayout(gl_contentPane);

		//Code generated by Eclipse due to the content placement
		gl_contentPane.setHorizontalGroup(
			gl_contentPane.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_contentPane.createSequentialGroup()
					.addContainerGap(220, Short.MAX_VALUE)
					.addComponent(panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(206))
				.addGroup(gl_contentPane.createSequentialGroup()
					.addGap(371)
					.addComponent(buyInvestmentFund)
					.addGap(250)
					.addComponent(cancelInvestmentFund)
					.addContainerGap(360, Short.MAX_VALUE))
				.addGroup(Alignment.TRAILING, gl_contentPane.createSequentialGroup()
					.addContainerGap(1283, Short.MAX_VALUE)
					.addComponent(variableAccount)
					.addGap(40))
		);
		gl_contentPane.setVerticalGroup(
			gl_contentPane.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_contentPane.createSequentialGroup()
					.addGap(106)
					.addComponent(panel, GroupLayout.PREFERRED_SIZE, 394, GroupLayout.PREFERRED_SIZE)
					.addGap(124)
					.addGroup(gl_contentPane.createParallelGroup(Alignment.BASELINE)
						.addComponent(buyInvestmentFund)
						.addComponent(cancelInvestmentFund))
					.addGap(47)
					.addComponent(variableAccount)
					.addContainerGap(149, Short.MAX_VALUE))
		);		
        
	}
}
