package es.unileon.ulebank.GUI.variableAccount;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.EventQueue;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.JTextPane;

import java.awt.Font;

import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.LayoutStyle.ComponentPlacement;

import java.awt.ScrollPane;

import javax.swing.JButton;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import javax.swing.JMenuBar;



public class VariableAccountGUI extends JFrame {

	private JPanel contentPane;
	private static VariableAccountGUI window;
	String[][] columnData;


	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		window= new VariableAccountGUI();
		
		window.setVisible(true);
		

		window.setResizable(false);
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        window.setLocation( 0,  0);


	}

	/**
	 * Create the frame.
	 */
	public VariableAccountGUI() {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 1276, 840);
		contentPane = new JPanel();

		setContentPane(contentPane);
		
		int width = this.getToolkit().getScreenSize().width;
        int height = this.getToolkit().getScreenSize().height;

        setSize( width , height );
		
		JTextPane name = new JTextPane();
		name.setFont(new Font("Lucida Grande", Font.PLAIN, 15));
		name.setText("Nombre");
		name.setOpaque(false);
		
		JTextPane surname = new JTextPane();
		surname.setFont(new Font("Lucida Grande", Font.PLAIN, 15));
		surname.setText("Apellidos");
		surname.setOpaque(false);
		
		JTextPane id = new JTextPane();
		id.setFont(new Font("Lucida Grande", Font.PLAIN, 15));
		id.setText("NIF");
		id.setOpaque(false);
		
		JTextPane address = new JTextPane();
		address.setFont(new Font("Lucida Grande", Font.PLAIN, 15));
		address.setText("Direccion");
		address.setOpaque(false);
		
		JTextPane accountNumber = new JTextPane();
		accountNumber.setFont(new Font("Lucida Grande", Font.BOLD, 17));
		accountNumber.setText("Numero de cuenta");
		accountNumber.setOpaque(false);
		
		
		JTextPane nameInfo = new JTextPane();
		nameInfo.setOpaque(false);
		nameInfo.setText("Ejemplo");
		
		JTextPane accountNumberInfo = new JTextPane();
		accountNumberInfo.setOpaque(false);
		accountNumberInfo.setText("Ejemplo");
		
		JTextPane surnameInfo = new JTextPane();
		surnameInfo.setOpaque(false);
		surnameInfo.setText("Ejemplo");
		
		JTextPane idInfo = new JTextPane();
		idInfo.setOpaque(false);
		idInfo.setText("Ejemplo");
		
		JTextPane addressInfo = new JTextPane();
		addressInfo.setOpaque(false);
		addressInfo.setText("Ejemplo");
		
		JPanel panel = new JPanel();
		
		
		JTable tableMovements = new JTable(new DefaultTableModel(
				new Object[][] {
					{"Ejemplo1", "Ejemplo1", "Ejemplo1", "Ejemplo1"},
					{"Ejemplo2", "Ejemplo2", "Ejemplo2", "Ejemplo2"},
					{"Ejemplo3", "Ejemplo3", "Ejemplo3", "Ejemplo3"},
					{"Ejemplo4", "Ejemplo4", "Ejemplo4", "Ejemplo4"},
					{"Ejemplo5", "Ejemplo5", "Ejemplo5", "Ejemplo5"},
					{"Ejemplo6", "Ejemplo6", "Ejemplo6", "Ejemplo6"},
					{"Ejemplo7", "Ejemplo7", "Ejemplo7", "Ejemplo7"},
					{"Ejemplo8", "Ejemplo8", "Ejemplo8", "Ejemplo8"},
					},
				new String[] {
					"Fecha","Tipo", "Empresa", "Datos", "Precio","Estado"
				}
			));
		tableMovements.setSurrendersFocusOnKeystroke(true);
		tableMovements.setColumnSelectionAllowed(true);
		tableMovements.setCellSelectionEnabled(true);
		tableMovements.getColumnModel().getColumn(0).setPreferredWidth(50);
		tableMovements.getColumnModel().getColumn(2).setPreferredWidth(200);
		tableMovements.setPreferredScrollableViewportSize(new Dimension(1000, 300));
		JScrollPane scrollPane = new JScrollPane(tableMovements);
		panel.add(scrollPane, BorderLayout.CENTER);
		
		JButton stocks = new JButton("Manejo de acciones");
		stocks.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				StockManagerGUI nextWindow = new StockManagerGUI();
				nextWindow.setVisible(true);
				setVisible(false);
			}
		});
		
		JButton investmentFund = new JButton("Manejo de fondos de inversion");
		investmentFund.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				InvestmentFundClientGUI nextWindow = new InvestmentFundClientGUI();
				nextWindow.setVisible(true);
				setVisible(false);
			}
		});
		


		
		
		GroupLayout gl_contentPane = new GroupLayout(contentPane);
		contentPane.setLayout(gl_contentPane);

		//Code generated by Eclipse due to the content placement
		gl_contentPane.setHorizontalGroup(
			gl_contentPane.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_contentPane.createSequentialGroup()
					.addGap(202)
					.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_contentPane.createSequentialGroup()
							.addComponent(panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addContainerGap())
						.addGroup(gl_contentPane.createSequentialGroup()
							.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
								.addComponent(name, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
								.addComponent(accountNumber, GroupLayout.PREFERRED_SIZE, 172, GroupLayout.PREFERRED_SIZE)
								.addComponent(surname, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(id, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(address, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(113)
							.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
								.addGroup(gl_contentPane.createSequentialGroup()
									.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
										.addComponent(nameInfo, GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
										.addComponent(accountNumberInfo, GroupLayout.PREFERRED_SIZE, 197, GroupLayout.PREFERRED_SIZE)
										.addComponent(surnameInfo, GroupLayout.PREFERRED_SIZE, 211, GroupLayout.PREFERRED_SIZE)
										.addComponent(idInfo, GroupLayout.PREFERRED_SIZE, 211, GroupLayout.PREFERRED_SIZE))
									.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
										.addGroup(gl_contentPane.createSequentialGroup()
											.addGap(180)
											.addComponent(investmentFund))
										.addGroup(gl_contentPane.createSequentialGroup()
											.addGap(213)
											.addComponent(stocks)))
									.addGap(442))
								.addGroup(gl_contentPane.createSequentialGroup()
									.addComponent(addressInfo, GroupLayout.PREFERRED_SIZE, 211, GroupLayout.PREFERRED_SIZE)
									.addContainerGap())))))
		);
		gl_contentPane.setVerticalGroup(
			gl_contentPane.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_contentPane.createSequentialGroup()
					.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_contentPane.createSequentialGroup()
							.addGap(122)
							.addGroup(gl_contentPane.createParallelGroup(Alignment.TRAILING)
								.addComponent(accountNumber, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(accountNumberInfo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
							.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
								.addComponent(name, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(nameInfo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(48)
							.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
								.addComponent(surname, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addGroup(gl_contentPane.createSequentialGroup()
									.addGap(13)
									.addComponent(surnameInfo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
							.addGap(48)
							.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
								.addComponent(id, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(idInfo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(51)
							.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
								.addComponent(address, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(addressInfo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(95))
						.addGroup(gl_contentPane.createSequentialGroup()
							.addGap(212)
							.addComponent(stocks)
							.addGap(84)
							.addComponent(investmentFund)
							.addGap(178)))
					.addComponent(panel, GroupLayout.PREFERRED_SIZE, 197, GroupLayout.PREFERRED_SIZE)
					.addGap(149))
		);

		
		
	}
}